import localFont from "next/font/local";
import ReactQueryProvider from "./utils/providers/ReactQueryProvider";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css'
// import "bootstrap/dist/js/bootstrap.bundle"

import "./globals.css";
import './style/main.css';
import NavBar from "./components/navBar/NavBar";
import Footer from "./components/footer/Footer";
import { CounterProvider } from "./Context/CounterContext";
import { Toaster } from "sonner";
import { ProfileDataProvider } from "./Context/ProfileContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Loopz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <ProfileDataProvider>
            <CounterProvider>
              <NavBar />
              {children}

              <Footer />
            </CounterProvider>
          </ProfileDataProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
